# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_swarsel 4BE7925262289B476DBBC17B76FD3810215AE097
  - &server_nixos age1zdjm8qa5t25mca0xxhhkpuh85mgg4l267mqjj2pdttksq7zg4unqdmqyp4
  - &server_surface age1zlnxraee6tddr07xn59mx5rdexw8qxryd53eqlsajasfhfy78fkq705dfg
  - &server_stand age1hkajkcje5xvg8jd4zj2e0s9tndpv36hwhn7p38x9lyq2z8g7v45q2nhlej
creation_rules:
  - path_regex: secrets/general/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *admin_swarsel
      age:
      - *server_nixos
      - *server_surface
      - *server_stand
  - path_regex: secrets/surface/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *admin_swarsel
      age:
      - *server_surface
