{
  description = "Minimal installer flake - automatically generated by SwarselSystems.org";

  inputs.swarsel.url = "./..";

  outputs = { swarsel, ... }: { nixosConfigurations = swarsel.nixosConfigurationsMinimal; };
}
